name: sticky_az_list
description: A ListView with sticky headers and an dynamic vertical Alphabet List on the Side which you can drag and tap to scroll to the first item starting with that letter in the list.
version: 0.0.4
repository: https://github.com/mattsouza26/sticky_az_list

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  flutter_sticky_header: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
